groups:
  - name: website
    projects:
      - name: website-fe
        repositoryUrl: git@github.com:Persokit/website-frontend.git
        host: persokit.local
        localIp: 10.24.18.1


  - name: auth-service
    projects:
      - name: auth-api
        repositoryUrl: git@github.com:Persokit/auth-api.git
        host: auth-api.persokit.local
        localIp: 10.24.18.2

      - name: auth-fe
        repositoryUrl: git@github.com:Persokit/auth-fe.git
        host: auth.persokit.local
        localIp: 10.24.18.4
