groups:
  - name: uab-sugedo
    projects:
      - name: sugedo-crm
        repositoryUrl: git@github.com:webnotion-inc/sgd-crm.git
        host: crm.sugedo.local
        localIp: 10.24.9.1

      - name: sugedo-website
        repositoryUrl: git@github.com:webnotion-inc/sgd-website.git
        host: sugedo.local
        localIp: 10.24.8.1

  - name: tripo
    projects:
      - name: tripo
        repositoryUrl: git@github.com:webnotion-inc/tripo.git
        host: tripo.local
        localIp: 10.24.14.1

  - name: webnotion
    projects:
        - name: webnotion-website
          repositoryUrl: git@github.com:webnotion-inc/webnotion-website.git
          host: webnotion.local
          localIp: 10.24.11.1
